#!/bin/bash

# Description: Displays information about ~/dotfiles

dotfiles_dir="${HOME}/Repos/github.com/mcrowley1121/dotfiles"

# Easier method, but might leave out hidden files unintentionally
#file_count_ls=$(ls "${dotfiles_dir}" | wc -l)

# More complex but explicitly prunes hidden .git directory and subfolders
file_count_find=$(find ~/Repos/github.com/mcrowley1121/dotfiles -mindepth 1 -path "${dotfiles_dir}"/.git -prune -or -print | wc -l)
today=$(date +%Y-%m-%d)

echo "==== Dotfiles Info ===="
echo "User: ${USER}"
echo "Path to dotfiles directory: ${dotfiles_dir}"
echo "Files tracked: ${file_count_find}"
echo "Date: ${today}"
