#!/bin/bash

# Description: Link dotfiles to home directory

mkdir -p ~/.config

ln -sf ~/Repos/github.com/mcrowley1121/dotfiles/bashrc ~/.bashrc
ln -sf ~/Repos/github.com/mcrowley1121/dotfiles/vimrc ~/.vimrc
ln -sf ~/Repos/github.com/mcrowley1121/dotfiles/starship.toml ~/.config/starship.toml
ln -sf ~/Repos/github.com/mcrowley1121/dotfiles/tmux.conf ~/.tmux.conf

echo "Dotfiles linked!"
