#!/bin/bash

# Description: Link dotfiles to home directory
set -euo pipefail

if ! command -v chezmoi >/dev/null; then
    sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply git@github.com:mcrowley1121/dotfiles.git
fi

exit 0
#mkdir -p ~/.config

#ln -sf ~/Repos/github.com/mcrowley1121/dotfiles/bashrc ~/.bashrc
#ln -sf ~/Repos/github.com/mcrowley1121/dotfiles/vimrc ~/.vimrc
#ln -sf ~/Repos/github.com/mcrowley1121/dotfiles/starship.toml ~/.config/starship.toml
#ln -sf ~/Repos/github.com/mcrowley1121/dotfiles/tmux.conf ~/.tmux.conf
#ln -sf ~/Repos/github.com/mcrowley1121/dotfiles/bash_profile ~/.bash_profile

#echo "Dotfiles linked!"
